apiVersion: v1
kind: Service
metadata:
  name: fad-app
  namespace: fadgw
  labels:
    app: fad-app
spec:
  ports:
  - name: 1234-tcp
    port: 1234
    protocol: TCP
    targetPort: 1234
  type: ClusterIP
  selector:
    deployment: fad-app
